import Foundation

// MARK: - Feed Exporter
/// Generates a shareable text summary of feed history.
enum FeedExporter {
    
    static func exportText(profile: BabyProfile?, feeds: [Feed]) -> String {
        var lines: [String] = []
        let dateFormatter = DateFormatter()
        dateFormatter.locale = Locale.current
        dateFormatter.dateStyle = .medium
        dateFormatter.timeStyle = .short
        
        // Header
        lines.append(NSLocalizedString("B-Fed Feed History", comment: "Export header"))
        lines.append("==================")
        lines.append("")
        
        if let profile = profile {
            lines.append("\(NSLocalizedString("Baby:", comment: "")) \(profile.babyName)")
            lines.append("\(NSLocalizedString("Age:", comment: "")) \(profile.ageDescription)")
            if let weight = profile.weightInKg {
                lines.append("\(NSLocalizedString("Weight:", comment: "")) \(String(format: "%.2f", weight)) kg")
            }
            lines.append("\(NSLocalizedString("Feeding:", comment: "")) \(profile.feedingType.displayName)")
            if let brand = profile.formulaBrand {
                lines.append("\(NSLocalizedString("Formula:", comment: "")) \(brand)")
            }
            lines.append("")
        }
        
        // Summary
        let calendar = Calendar.current
        let grouped = Dictionary(grouping: feeds) { feed in
            calendar.startOfDay(for: feed.startTime)
        }
        
        lines.append(NSLocalizedString("Summary", comment: "Export section header"))
        lines.append("\(NSLocalizedString("Total feeds:", comment: "")) \(feeds.count)")
        lines.append("\(NSLocalizedString("Total days:", comment: "")) \(grouped.count)")
        if !feeds.isEmpty {
            let totalAmount = feeds.reduce(0) { $0 + $1.amount }
            lines.append("\(NSLocalizedString("Total amount:", comment: "")) \(Int(totalAmount)) ml")
            lines.append("\(NSLocalizedString("Average per feed:", comment: "")) \(Int(totalAmount / Double(feeds.count))) ml")
        }
        lines.append("")
        
        // Daily detail
        let sortedDates = grouped.keys.sorted { $0 > $1 }
        for date in sortedDates {
            let dayFeeds = grouped[date] ?? []
            let dayTotal = dayFeeds.reduce(0) { $0 + $1.amount }
            let dateString = dateFormatter.string(from: date).prefix(10)
            
            lines.append("\(dateString) — \(dayFeeds.count) \(NSLocalizedString("feeds", comment: "")), \(Int(dayTotal)) ml")
            
            for feed in dayFeeds.sorted(by: { $0.startTime > $1.startTime }) {
                let time = dateFormatter.string(from: feed.startTime)
                let duration = feed.duration.map { " (\(Int($0/60))m)" } ?? ""
                let status = feed.completed ? "" : " [\(NSLocalizedString("left some", comment: ""))]"
                lines.append("  • \(time): \(Int(feed.amount)) ml\(duration)\(status)")
            }
            lines.append("")
        }
        
        lines.append(NSLocalizedString("Generated by B-Fed", comment: "Export footer"))
        return lines.joined(separator: "\n")
    }
    
    static func exportFilename() -> String {
        let formatter = DateFormatter()
        formatter.dateFormat = "yyyy-MM-dd"
        return "b-fed-history-\(formatter.string(from: Date())).txt"
    }
}
