import Foundation

// MARK: - Feed Exporter
/// Generates a shareable text summary of feed history.
enum FeedExporter {
    
    static func exportText(profile: BabyProfile?, feeds: [Feed]) -> String {
        var lines: [String] = []
        let dateFormatter = DateFormatter()
        dateFormatter.locale = Locale.current
        dateFormatter.dateStyle = .medium
        dateFormatter.timeStyle = .short
        
        // Header
        lines.append("B-Fed Feed History")
        lines.append("==================")
        lines.append("")
        
        if let profile = profile {
            lines.append("Baby: \(profile.babyName)")
            lines.append("Age: \(profile.ageDescription)")
            if let weight = profile.weightInKg {
                lines.append("Weight: \(String(format: "%.2f", weight)) kg")
            }
            lines.append("Feeding: \(profile.feedingType.displayName)")
            if let brand = profile.formulaBrand {
                lines.append("Formula: \(brand)")
            }
            lines.append("")
        }
        
        // Summary
        let calendar = Calendar.current
        let grouped = Dictionary(grouping: feeds) { feed in
            calendar.startOfDay(for: feed.startTime)
        }
        
        lines.append("Summary")
        lines.append("Total feeds: \(feeds.count)")
        lines.append("Total days: \(grouped.count)")
        if !feeds.isEmpty {
            let totalAmount = feeds.reduce(0) { $0 + $1.amount }
            lines.append("Total amount: \(Int(totalAmount)) ml")
            lines.append("Average per feed: \(Int(totalAmount / Double(feeds.count))) ml")
        }
        lines.append("")
        
        // Daily detail
        let sortedDates = grouped.keys.sorted { $0 > $1 }
        for date in sortedDates {
            let dayFeeds = grouped[date] ?? []
            let dayTotal = dayFeeds.reduce(0) { $0 + $1.amount }
            let dateString = dateFormatter.string(from: date).prefix(10)
            
            lines.append("\(dateString) — \(dayFeeds.count) feeds, \(Int(dayTotal)) ml")
            
            for feed in dayFeeds.sorted(by: { $0.startTime > $1.startTime }) {
                let time = dateFormatter.string(from: feed.startTime)
                let duration = feed.duration.map { " (\(Int($0/60))m)" } ?? ""
                let status = feed.completed ? "" : " [left some]"
                lines.append("  • \(time): \(Int(feed.amount)) ml\(duration)\(status)")
            }
            lines.append("")
        }
        
        lines.append("Generated by B-Fed")
        return lines.joined(separator: "\n")
    }
    
    static func exportFilename() -> String {
        let formatter = DateFormatter()
        formatter.dateFormat = "yyyy-MM-dd"
        return "b-fed-history-\(formatter.string(from: Date())).txt"
    }
}
